cmake_minimum_required(VERSION 3.13)
project(stratum)

set(CMAKE_CXX_STANDARD 14)

include_directories(.)
include_directories(algos)
include_directories(algos/ar2)
include_directories(algos/ar2/sj)
include_directories(algos/blake2)
include_directories(algos/SWIFFTX)
include_directories(iniparser/src)
include_directories(sha3)

add_executable(stratum
        algos/ar2/sj/scrypt-jane-hash.h
        algos/ar2/sj/scrypt-jane-hash_skein512.h
        algos/ar2/sj/scrypt-jane-mix_salsa64-avx.h
        algos/ar2/sj/scrypt-jane-mix_salsa64-avx2.h
        algos/ar2/sj/scrypt-jane-mix_salsa64-sse2.h
        algos/ar2/sj/scrypt-jane-mix_salsa64-ssse3.h
        algos/ar2/sj/scrypt-jane-mix_salsa64-xop.h
        algos/ar2/sj/scrypt-jane-mix_salsa64.h
        algos/ar2/sj/scrypt-jane-pbkdf2.h
        algos/ar2/sj/scrypt-jane-portable-x86.h
        algos/ar2/sj/scrypt-jane-portable.h
        algos/ar2/sj/scrypt-jane-romix-basic.h
        algos/ar2/sj/scrypt-jane-romix-template.h
        algos/ar2/sj/scrypt-jane-romix.h
        algos/ar2/sj/scrypt-jane-salsa64.h
        algos/ar2/sj/scrypt-jane-test-vectors.h
        algos/ar2/ar2-scrypt-jane.c
        algos/ar2/ar2-scrypt-jane.h
        algos/ar2/argon2.c
        algos/ar2/argon2.h
        algos/ar2/core.c
        algos/ar2/core.h
        algos/ar2/encoding.c
        algos/ar2/encoding.h
        algos/ar2/opt.c
        algos/ar2/thread.c
        algos/ar2/thread.h
        algos/blake2/blake2-impl.h
        algos/blake2/blake2.h
        algos/blake2/blake2b.c
        algos/blake2/blamka-round-opt.h
        algos/blake2/blamka-round-ref.h
        algos/SWIFFTX/inttypes.h
        algos/SWIFFTX/stdbool.h
        algos/SWIFFTX/stdint.h
        algos/SWIFFTX/SWIFFTX.c
        algos/SWIFFTX/SWIFFTX.h
        algos/a5a.c
        algos/a5a.h
        algos/a5amath.c
        algos/a5amath.h
        algos/aergo.c
        algos/aergo.h
        algos/allium.c
        algos/allium.h
        algos/argon2a.c
        algos/argon2a.h
        algos/argon2d-dyn.c
        algos/argon2d-dyn.h
        algos/bastion.c
        algos/bastion.h
        algos/bitcore.c
        algos/bitcore.h
        algos/blake.c
        algos/blake.h
        algos/blake2b.c
        algos/blake2b.h
        algos/blake2s.c
        algos/blake2s.h
        algos/blakecoin.c
        algos/blakecoin.h
        algos/bmw.c
        algos/bmw.h
        algos/c11.c
        algos/c11.h
        algos/common.h
        algos/deep.c
        algos/deep.h
        algos/drop.c
        algos/drop.h
        algos/exosis.c
        algos/exosis.h
        algos/fresh.c
        algos/fresh.h
        algos/gost.c
        algos/gost.h
        algos/groestl.c
        algos/groestl.h
        algos/hex.c
        algos/hex.h
        algos/hive.c
        algos/hive.h
        algos/hmq17.c
        algos/hmq17.h
        algos/hsr14.c
        algos/hsr14.h
        algos/jha.c
        algos/jha.h
        algos/keccak.c
        algos/keccak.h
        algos/lbk3.c
        algos/lbk3.h
        algos/lbry.c
        algos/lbry.h
        algos/luffa.c
        algos/luffa.h
        algos/Lyra2-z.c
        algos/Lyra2-z.h
        algos/Lyra2.c
        algos/Lyra2.h
        algos/lyra2re.c
        algos/lyra2re.h
        algos/lyra2v2.c
        algos/lyra2v2.h
        algos/lyra2v3.c
        algos/lyra2v3.h
        algos/lyra2z.c
        algos/lyra2z.h
        algos/m7m.c
        algos/m7m.h
        algos/magimath.cpp
        algos/magimath.h
        algos/neoscrypt.c
        algos/neoscrypt.h
        algos/nist5.c
        algos/nist5.h
        algos/pentablake.c
        algos/pentablake.h
        algos/phi.c
        algos/phi.h
        algos/phi2.c
        algos/phi2.h
        algos/polytimos.c
        algos/polytimos.h
        algos/pomelo.c
        algos/pomelo.h
        algos/quark.c
        algos/quark.h
        algos/qubit.c
        algos/qubit.h
        algos/rainforest.c
        algos/rainforest.h
        algos/scrypt.c
        algos/scryptn.c
        algos/scryptn.h
        algos/sha256.c
        algos/sha256.h
        algos/sha256_Y.c
        algos/sha256_Y.h
        algos/sha256q.c
        algos/sha256q.h
        algos/sha256t.c
        algos/sha256t.h
        algos/sib.c
        algos/sib.h
        algos/skein.c
        algos/skein.h
        algos/skein2.c
        algos/skein2.h
        algos/skunk.c
        algos/skunk.h
        algos/sm3.c
        algos/sm3.h
        algos/sonoa.c
        algos/sonoa.h
        algos/Sponge.c
        algos/Sponge.h
        algos/sysendian.h
        algos/timetravel.c
        algos/timetravel.h
        algos/tribus.c
        algos/tribus.h
        algos/veltor.c
        algos/veltor.h
        algos/velvet.c
        algos/velvet.h
        algos/vitalium.c
        algos/vitalium.h
        algos/whirlpool.c
        algos/whirlpool.h
        algos/whirlpoolx.c
        algos/whirlpoolx.h
        algos/x11.c
        algos/x11.h
        algos/x11evo.c
        algos/x11evo.h
        algos/x12.c
        algos/x12.h
        algos/x13.c
        algos/x13.h
        algos/x14.c
        algos/x14.h
        algos/x15.c
        algos/x15.h
        algos/x16r.c
        algos/x16r.h
        algos/x16s.c
        algos/x16s.h
        algos/x17.c
        algos/x17.h
        algos/x22i.c
        algos/x22i.h
        algos/xevan.c
        algos/xevan.h
        algos/yescrypt-opt.c
        algos/yescrypt-platform.c
        algos/yescrypt.c
        algos/yescrypt.h
        algos/zr5.c
        algos/zr5.h
        iniparser/src/dictionary.c
        iniparser/src/dictionary.h
        iniparser/src/iniparser.c
        iniparser/src/iniparser.h
        iniparser/test/iniexample.c
        iniparser/test/parse.c
        sha3/aes_helper.c
        sha3/blake2b.c
        sha3/blake2b.h
        sha3/blake2s.c
        sha3/blake2s.h
        sha3/hamsi_helper.c
        sha3/haval_helper.c
        sha3/md_helper.c
        sha3/sph_blake.c
        sha3/sph_blake.h
        sha3/sph_bmw.c
        sha3/sph_bmw.h
        sha3/sph_cubehash.c
        sha3/sph_cubehash.h
        sha3/sph_echo.c
        sha3/sph_echo.h
        sha3/sph_fugue.c
        sha3/sph_fugue.h
        sha3/sph_groestl.c
        sha3/sph_groestl.h
        sha3/sph_hamsi.c
        sha3/sph_hamsi.h
        sha3/sph_haval.c
        sha3/sph_haval.h
        sha3/sph_hefty1.c
        sha3/sph_hefty1.h
        sha3/sph_jh.c
        sha3/sph_jh.h
        sha3/sph_keccak.c
        sha3/sph_keccak.h
        sha3/sph_luffa.c
        sha3/sph_luffa.h
        sha3/sph_ripemd.c
        sha3/sph_ripemd.h
        sha3/sph_sha2.c
        sha3/sph_sha2.h
        sha3/sph_sha2big.c
        sha3/sph_shabal.c
        sha3/sph_shabal.h
        sha3/sph_shavite.c
        sha3/sph_shavite.h
        sha3/sph_simd.c
        sha3/sph_simd.h
        sha3/sph_skein.c
        sha3/sph_skein.h
        sha3/sph_tiger.c
        sha3/sph_tiger.h
        sha3/sph_types.h
        sha3/sph_whirlpool.c
        sha3/sph_whirlpool.h
        base58.cpp
        client.cpp
        client.h
        client_core.cpp
        client_difficulty.cpp
        client_submit.cpp
        coinbase.cpp
        coind.cpp
        coind.h
        coind_aux.cpp
        coind_submit.cpp
        coind_template.cpp
        db.cpp
        db.h
        job.cpp
        job.h
        job_core.cpp
        job_send.cpp
        json.cpp
        json.h
        list.cpp
        merkle.cpp
        object.cpp
        object.h
        remote.cpp
        remote.h
        remote_template.cpp
        rpc.cpp
        rpc.h
        rpc_curl.cpp
        share.cpp
        share.h
        socket.cpp
        socket.h
        stratum.cpp
        stratum.h
        user.cpp
        util.cpp
        util.h)
