[TCP]
server = ncpool.net
port = 3333
password = LHd4iB6IQxYCqTHt79CBRgtSlsWLTRKM

[SQL]
host = localhost
database = yiimpfrontend
username = stratum
password = 3ZvzjArQnHVFJ5M1EnjEA4VEQixxB5NW

[STRATUM]
algo = sha256
difficulty = 1
min_diff=1.0
max_diff=1000
max_ttf = 40000
reconnect = 1

